version: '3.8'

services:
  app:
    image: mohammedelweza/todo-app:latest
    container_name: app
    ports:
      - "4000:4000"
    environment:
      - mongoDbUrl=mongodb+srv://moahmed9899:ABu5pnbhQ7eJ1jWL@cluster0.nysnarj.mongodb.net/todo-app?retryWrites=true&w=majority
    restart: always
  
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - ~/.docker/config.json:/config.json
    command:  --interval 30
    restart: always

